function dsge_estim_tbl_disp(xparams, estim_params_names, xstderr, log_likelihood, optim_names)


fprintf('POINT ESTIMATES\n')
disp(array2table([xparams; log_likelihood]...
                ,'RowNames',[estim_params_names;'Log-Lik']...
                ,'VariableNames', optim_names...
                ));
fprintf('STANDARD ERRORS\n')
disp(array2table([xstderr; log_likelihood]...
                ,'RowNames',[erase(estim_params_names,"transformed_");'Log-Lik']...
                ,'VariableNames', optim_names...
                ));