function f = ireland2004_f(STEADY_STATE,PARAMS)
% function f = ireland2004_f(STEADY_STATE,PARAMS)
% Model equations, automatically generated by ireland2004_preprocessing.m

% Evaluate numerical values for parameters from PARAMS
BETA = PARAMS(1);
PSI = PARAMS(2);
ALPHA_PI = PARAMS(3);
ALPHA_X = PARAMS(4);
RHO_A = PARAMS(5);
RHO_E = PARAMS(6);
OMEGA = PARAMS(7);
RHO_PI = PARAMS(8);
RHO_G = PARAMS(9);
RHO_X = PARAMS(10);

% Evaluate numerical values for steady-state from STEADY_STATE (this also updates endogenous parameters)
steady_state_ahat = STEADY_STATE(1);
steady_state_ehat = STEADY_STATE(2);
steady_state_zhat = STEADY_STATE(3);
steady_state_xhat = STEADY_STATE(4);
steady_state_pihat = STEADY_STATE(5);
steady_state_yhat = STEADY_STATE(6);
steady_state_ghat = STEADY_STATE(7);
steady_state_rhat = STEADY_STATE(8);

% Evaluate exogenous variables
eta_a = 0;
eta_e = 0;
eta_z = 0;
eta_r = 0;

% Set all endogenous variables to steady-state values
ahat_back = steady_state_ahat; ahat_curr = steady_state_ahat; ahat_fwrd = steady_state_ahat;
ehat_back = steady_state_ehat; ehat_curr = steady_state_ehat; ehat_fwrd = steady_state_ehat;
zhat_back = steady_state_zhat; zhat_curr = steady_state_zhat; zhat_fwrd = steady_state_zhat;
xhat_back = steady_state_xhat; xhat_curr = steady_state_xhat; xhat_fwrd = steady_state_xhat;
pihat_back = steady_state_pihat; pihat_curr = steady_state_pihat; pihat_fwrd = steady_state_pihat;
yhat_back = steady_state_yhat; yhat_curr = steady_state_yhat; yhat_fwrd = steady_state_yhat;
ghat_back = steady_state_ghat; ghat_curr = steady_state_ghat; ghat_fwrd = steady_state_ghat;
rhat_back = steady_state_rhat; rhat_curr = steady_state_rhat; rhat_fwrd = steady_state_rhat;

% Write out model equations
f(1) = eta_a - ahat_curr + RHO_A*ahat_back;
f(2) = eta_e - ehat_curr + RHO_E*ehat_back;
f(3) = eta_z - zhat_curr;
f(4) = pihat_fwrd - rhat_curr - xhat_curr + ALPHA_X*xhat_back - xhat_fwrd*(ALPHA_X - 1) + ahat_curr*(OMEGA - 1)*(RHO_A - 1);
f(5) = PSI*xhat_curr - pihat_curr - ehat_curr + BETA*(ALPHA_PI*pihat_back - pihat_fwrd*(ALPHA_PI - 1));
f(6) = yhat_curr - xhat_curr - OMEGA*ahat_curr;
f(7) = yhat_curr - yhat_back - ghat_curr + zhat_curr;
f(8) = eta_r + rhat_back - rhat_curr + RHO_G*ghat_curr + RHO_PI*pihat_curr + RHO_X*xhat_curr;

end % function end 
