function g1 = ireland2004_g1(STEADY_STATE,PARAMS)
% function g1 = ireland2004_g1(STEADY_STATE,PARAMS)
% Dynamic model Jacobian, automatically generated by ireland2004_preprocessing.m

% Evaluate numerical values for parameters from PARAMS
BETA = PARAMS(1);
PSI = PARAMS(2);
ALPHA_PI = PARAMS(3);
ALPHA_X = PARAMS(4);
RHO_A = PARAMS(5);
RHO_E = PARAMS(6);
OMEGA = PARAMS(7);
RHO_PI = PARAMS(8);
RHO_G = PARAMS(9);
RHO_X = PARAMS(10);

% Evaluate numerical values for steady-state from STEADY_STATE (this also updates endogenous parameters)
steady_state_ahat = STEADY_STATE(1);
steady_state_ehat = STEADY_STATE(2);
steady_state_zhat = STEADY_STATE(3);
steady_state_xhat = STEADY_STATE(4);
steady_state_pihat = STEADY_STATE(5);
steady_state_yhat = STEADY_STATE(6);
steady_state_ghat = STEADY_STATE(7);
steady_state_rhat = STEADY_STATE(8);

% Evaluate exogenous variables
eta_a = 0;
eta_e = 0;
eta_z = 0;
eta_r = 0;

% Set all endogenous variables to steady-state values
ahat_back = steady_state_ahat; ahat_curr = steady_state_ahat; ahat_fwrd = steady_state_ahat;
ehat_back = steady_state_ehat; ehat_curr = steady_state_ehat; ehat_fwrd = steady_state_ehat;
zhat_back = steady_state_zhat; zhat_curr = steady_state_zhat; zhat_fwrd = steady_state_zhat;
xhat_back = steady_state_xhat; xhat_curr = steady_state_xhat; xhat_fwrd = steady_state_xhat;
pihat_back = steady_state_pihat; pihat_curr = steady_state_pihat; pihat_fwrd = steady_state_pihat;
yhat_back = steady_state_yhat; yhat_curr = steady_state_yhat; yhat_fwrd = steady_state_yhat;
ghat_back = steady_state_ghat; ghat_curr = steady_state_ghat; ghat_fwrd = steady_state_ghat;
rhat_back = steady_state_rhat; rhat_curr = steady_state_rhat; rhat_fwrd = steady_state_rhat;

% Initialize first dynamic Jacobian g1
g1 = zeros(8, 28);
% Evaluate non-zero entries in g1
g1(1,3) = RHO_A;
g1(2,4) = RHO_E;
g1(7,5) = -1;
g1(8,6) = 1;
g1(4,7) = ALPHA_X;
g1(5,8) = ALPHA_PI*BETA;
g1(3,9) = -1;
g1(7,9) = 1;
g1(7,10) = -1;
g1(8,10) = RHO_G;
g1(1,11) = -1;
g1(4,11) = (OMEGA - 1)*(RHO_A - 1);
g1(6,11) = -OMEGA;
g1(2,12) = -1;
g1(5,12) = -1;
g1(6,13) = 1;
g1(7,13) = 1;
g1(4,14) = -1;
g1(8,14) = -1;
g1(4,15) = -1;
g1(5,15) = PSI;
g1(6,15) = -1;
g1(8,15) = RHO_X;
g1(5,16) = -1;
g1(8,16) = RHO_PI;
g1(4,23) = 1 - ALPHA_X;
g1(4,24) = 1;
g1(5,24) = -BETA*(ALPHA_PI - 1);
g1(1,25) = 1;
g1(2,26) = 1;
g1(3,27) = 1;
g1(8,28) = 1;

end % function end 
